project/crm/urls.py
from django.conf.urls import url

from . import views

app_name = 'crm'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts/', views.charts, name='charts'),
    url(r'^charts_get/', views.charts_get, name='charts_get'),
    url(r'^clientAutoComplete/', views.client_auto, name='clientAuto'),
]

project/project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from welcome import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^welcome/', include('welcome.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^crm/', include('crm.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/crm/models.py
from __future__ import unicode_literals

from django.db import models

    
class Role(models.Model):
    name = models.CharField(max_length=20, blank=True, null=True)
    access = models.IntegerField(blank=True, null=True)
    def __unicode__(self):
    	return self.name


class Client(models.Model):
    id_role = models.ForeignKey(Role, on_delete=models.CASCADE)
    login = models.CharField(max_length=20, blank=True, null=True)
    full_name = models.CharField(max_length=30, blank=True, null=True)
    pwd = models.CharField(max_length=10, blank=True, null=True)
    begindate = models.DateField(blank=True, null=True)
    birthdate = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    site = models.CharField(max_length=50, blank=True, null=True)
    SOCIAL_STATUS = (
        (1,'school'),
        (2,'student'),
        (3,'worker'),
        (0,'dependent')
    )
    SEX = (
        (1,'male'),
        (0,'female')
    )
    social_status = models.CharField(choices=SOCIAL_STATUS, max_length=2,default=0)
    sex = models.CharField(choices=SEX,  max_length=2,default=1)
    def __unicode__(self):
        return self.login

class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    fee = models.FloatField(blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    def __unicode__(self):
        return self.name

class Visit (models.Model):
    id_client = models.ForeignKey(Client, on_delete=models.CASCADE)
    id_event  = models.ForeignKey(Event, on_delete=models.CASCADE)
    id_manager = models.ForeignKey('auth.User', default=1)
    date = models.DateField(blank=True, null=True)
    note = models.CharField(max_length=50, blank=True, null=True)
    def __unicode__(self):
        return str(self.pk)

project/crm/forms.py
from django import forms
from .models import Client,Visit,Event,Role

class VisitForm(forms.ModelForm):
    class Meta:
        model = Visit
        fields = ('id_event','note',)

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('id_role','login','birthdate','phone','social_status','sex',)

project/crm/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import VisitForm, ClientForm
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from qsstats import QuerySetStats

from django.core import serializers
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Client,Visit,Event
from django.db import connection

# Create your views here.
#-*- coding:utf-8 -*-

@login_required(login_url='/registration/login/')
def index(request):
    clForm = ClientForm()
    form = VisitForm()
    form.fields['id_event'].label = "Событие"
    form.fields['note'].label = "Примечания"
    client = Client.objects.all()
    if request.method == "POST":
        clForm = ClientForm(request.POST)
        form = VisitForm(request.POST)
        form.fields['id_event'].label = "Событие"
        form.fields['note'].label = "Примечания"
        if form.is_valid():
            visit = form.save(commit=False)
            visit.date = timezone.now()
            if request.user.is_authenticated():
                me = request.user
            visit.id_manager = me
            # v11 = request.POST.get(u'id_client')
            v1 = Client.objects.get(login=request.POST.get(u'id_client'))
            visit.id_client = v1
            v3 = visit.id_event
            if visit.id_client.pk ==2:
                f1 = False
            else:
                f1 = True
            v2 = visit.date
            if Visit.objects.filter(id_client=v1, date=v2, id_event=v3).exists() and f1:
                print (v1, v2, v3, f1,'was')
                form.add_error(None, 'Такой посетитель уже учтен')
                return render(request, 'crm/manager.html',{'form': form,'Clients': client})
            else:
                print (v1, v2, v3, f1,'was not')
                visit.save()
                form.add_error(None, 'Посетитель учтен')
                return render(request, 'crm/manager.html',{'form': form,'Clients': client})
        else:
            form = VisitForm()
        if clForm.is_valid():
            client = clForm.save()
            return render(request, 'crm/manager.html',{'form': form,'Clients': client})
    return render(request, 'crm/manager.html',{'form': form,'Clients': client})


@login_required(login_url='/registration/login/')
def charts(request):
    data = ClientForm(request.POST)
    return render(request, 'crm/charts.html',{'clientForm': data})

def charts_get(request):
    date1=request.POST.get(u'id1')
    date2=request.POST.get(u'id2')
    def dictfetchall(cursor):
        columns = [col[0] for col in cursor.description]
        return [
            dict(zip(columns, row))
            for row in cursor.fetchall()
        ]

    with connection.cursor() as c:
        c.execute('select date, count(id) as visits from crm_visit where date between \''+date1+'\' and \''+date2+'\' group by date order by date')
        return JsonResponse(dictfetchall(c), safe=False)
    return render(request, 'crm/charts.html')


def client_record(request):
    wanted = request.POST.get('cl_id')
    visit = Visit.objects.filter(id_client=wanted).values('id_client__login','date','id_event__name')
    # visit = Visit.objects.filter(id_client=wanted)
    # data = serializers.serialize('json', visit, fields('id_client','date','id_event'))
    # return JsonResponse(visit, safe=False)
    return JsonResponse({'listVal': list(visit)})

def client_auto(request):
    term = request.POST.get('keyword')
    listClients = Client.objects.filter(login__icontains=term).values('login','phone','birthdate','id')
    return JsonResponse({'listVal':list(listClients)})

project/crm/templates/crm/charts.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}
<div class="container ">
	<h2>Графики</h2>
	<div id="tabs">
    <ul>
      <li><a href="#tabs-1">Анализ посещений</a></li>
      <li><a href="#tabs-2">Заглушка</a></li>
    </ul>

    <div id="tabs-1">
      <p>C: <input type="text" class="datepicker" id="dateRange1"></p>
      <p>По: <input type="text" class="datepicker" id="dateRange2"></p>
      <button class="btn btn-default get_to_da_JSON">Показать графики</button>
      <div id="chart_div" style="width: 900px; height: 250px"></div>
    </div>

    <div id="tabs-2">    
      
    </div>
  </div>
</div>
{% endblock %}

project/crm/templates/crm/manager.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<!--
<style>
	.layer {
		overflow: scroll; /* Добавляем полосы прокрутки */
		width: 300px; /* Ширина блока */
		height: 400px; /* Высота блока */
		padding: 5px; /* Поля вокруг текста */
		border: solid 1px black; /* Параметры рамки */
	} 
</style>
-->

<div class="container">
<div class="col-md-24">
	<div class="col-md-8">
	<h2>Manager</h2>
	<h3>Новый посетитель</h3>
	{% for error in form.non_field_errors %}
		<span class="error-message">{{ error }}</span>
	{% endfor %}
	<form method="POST" class="form-horizontal">{% csrf_token %}
		<div class="row">
			<div class="col-md-16" style="padding: 1px;">
				<label for="id_client">Клиент:</label>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				<input name="id_client" required id="id_id_client">
				<div class="clients_list"></div>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				<label for="id_event">Событие:</label>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				{{form.id_event}}
			</div>
			<div class="col-md-16" style="padding: 1px;">
				<label for="note">Примечание:</label>
			</div>
			<div class="col-md-16" style="padding: 1px;">
				{{form.note}}
			</div>
			<div class="col-md-16" style="padding: 5px;">
				<button type="submit" class="btn btn-large save">Добавить</button>
			</div>
		</div>
	</form>
	<h3>Добавить клиента</h3>
	<form method="POST" class="post-form">{% csrf_token %}
		{{clientForm}}
	</form>
	</div>
	<div class="col-md-16 ">
		<div class="layer">
			<table class="table table-bordered">
			<tr class="tableHead">
				<td>Имя</td>
				<td>Телефон</td>
				<td>Возраст</td>
			</tr>
			{% for client in Clients %}
			<tr class="visitor-row" id="{{client.id}}">
				<td class="visitor-login">{{client.login}}</td>
				<td>{{client.phone}}</td>
				<td>{{client.begindate}}</td>

			</tr>
			{% endfor %}
		</table>
		</div>
	</div>
</div>
</div>



{% endblock %}