project/crm/urls.py
from django.conf.urls import url

from . import views

app_name = 'crm'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts/', views.charts, name='charts'),
    url(r'^charts_get/', views.charts_get, name='charts_get'),
    url(r'^clientAutoComplete/', views.client_auto, name='clientAuto'),
]

project/project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from welcome import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^welcome/', include('welcome.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^crm/', include('crm.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/registration/urls.py
from django.conf.urls import url

from . import views


app_name = 'registration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^reg/$', views.registration, name='reg'),
]

project/welcome/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'welcome'
urlpatterns = [
    # url(r'^clientDetail/(?P<id>\w{0,50})/$', views.client_detail, name='clientDetail'),
    url(r'^clientDetail/', views.client_detail, name='clientDetail'),
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    
    url(r'^registration/', views.index, name='reg'),
    url(r'^test/$', views.test, name='test'),

]

project/welcome/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

# Create your models here.

project/welcome/forms.py
from django import forms
from .models import Post 

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

project/welcome/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils import timezone

from .models import Post
from crm.models import Client, Visit
from .forms import PostForm
from django.core import serializers

# def index(request):
# 	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
# 	return render(request, 'project/base.html',{'posts': posts})

def index(request):
	client = Client.objects.all()
	visit = Visit.objects.all()
	content = {
		'Clients' : client,
		'Visits' : visit
	}
	return render(request, 'welcome/welcome.html', content)

def client_detail(request):
	wanted = request.POST.get('cl_id')
	visit = Visit.objects.filter(id_client=wanted).values('id_client__login','date','id_event__name')
	return JsonResponse({'listVal': list(visit)})
	# visit = Visit.objects.filter(id_client=wanted)
	# data = serializers.serialize('json', visit)
	# return JsonResponse(data, safe=False)

def test(request):
    return render(request, 'welcome/test.html')

def post_detail(request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'welcome/post_detail.html', {'post': post})

def post_new(request):
        form = PostForm()
        return render(request, 'welcome/post_edit.html', {'form': form})
        

project/welcome/templates/welcome/index.html
<html>
<head>
</head>

<body>
	<h1>Это страница приветствия</h1>
	<a href="{% url 'welcome:post_new' %}" class="top-menu">newPost</a>
    {% for post in posts %}
        <div>
            <p>published: {{ post.published_date }}</p>
            <h1><a href="{% url 'welcome:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}

    <div>
		<a href="{% url 'registration:index' %}"><button>Тест</button></a>
    </div>
	
</body>	
</html>

project/welcome/templates/welcome/post_detail.html
<div class="post">
    {% if post.published_date %}
        <div class="date">
            {{ post.published_date }}
        </div>
    {% endif %}
    <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
</div>

project/welcome/templates/welcome/post_edit.html
<h1>New post</h1>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>

project/welcome/templates/welcome/test.html
<h1>Test-registration</h1>
{% block content %}
{% endblock %}

project/welcome/templates/welcome/welcome.html
{% extends 'project/base.html' %}
{% load static %}
{% block content %}

<div class="container">
	<div class="row">
		<h2>Приветствуем на главной странице</h2>
		<div class="col-md-12">
			<div class="layer">
				<caption>Список клиентов</caption>
				<table class="table table-bordered">
					<tr class="tableHead">
						<td>Имя</td>
						<td>Телефон</td>
						<td>Возраст</td>
					</tr>
					{% for client in Clients %}
					<tr class="" id="{{client.id}}">
						<td><a href="">{{client.login}}</a></td>
						<td>{{client.phone}}</td>
						<td>{{client.begindate}}</td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
		<div class="col-md-12">
			<div class="layer">
				<caption>Список посещений</caption>
				<table class="table table-bordered">
					<tr class="tableHead">
						<td>Имя</td>
						<td>Дата</td>
						<td>Событие</td>
					</tr>
					{% for visit in Visits %}
					<tr>
						<td>{{visit.id_client}}</td>
						<td>{{visit.date}}</td>
						<td>{{visit.id_event}}</td>

					</tr>
					{% endfor %}
				</table>	
			</div>		
		</div>
	</div>
</div>



{% endblock %}