project/crm/urls.py
from django.conf.urls import url

from . import views

app_name = 'crm'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^charts/', views.charts, name='charts'),
    url(r'^charts_get/', views.charts_get, name='charts_get'),
    url(r'^clientAutoComplete/', views.client_auto, name='clientAuto'),
]

project/project/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from welcome import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index),
    url(r'^admin/', admin.site.urls),
    url(r'^registration/', include('registration.urls')),
    url(r'^welcome/', include('welcome.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^crm/', include('crm.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/registration/urls.py
from django.conf.urls import url

from . import views


app_name = 'registration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^reg/$', views.registration, name='reg'),
]

project/welcome/urls.py
from django.conf.urls import url,include
from . import views

app_name = 'welcome'
urlpatterns = [
    # url(r'^clientDetail/(?P<id>\w{0,50})/$', views.client_detail, name='clientDetail'),
    url(r'^clientDetail/', views.client_detail, name='clientDetail'),
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    
    url(r'^registration/', views.index, name='reg'),
    url(r'^test/$', views.test, name='test'),

]

project/project/templates/project/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang='ru'>
<head>
    <meta charset='UTF-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel='stylesheet' href='{% static 'project/css/bootstrap.min.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/font-awesome.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/jquery-ui.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/jquery-ui.theme.css' %}'>
    <link rel='stylesheet' href='{% static 'project/css/coreStyle.css' %}'>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <title>{% block title %}{% endblock %}</title>
    {% block style %}{% endblock %}
    {% block script %}
        <script src="{% static "project/js/jquery.min.js" %}"></script>
        <script src="{% static "project/js/jquery-ui.js" %}"></script>
        <script src="{% static "project/js/app.js" %}"></script>
        {% csrf_token %}
        <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        </script>
    {% endblock %}
</head>

<body>

{% block header %}
    {% include 'project/header.html' %}
{% endblock %}

<!--Разметка-->

{% block content %}
{% endblock %}




<!--Подвал-->
{% block footer %}
    {% include 'project/footer.html' %}
{% endblock %}

</body>
</html>

project/project/templates/project/footer.html
{% block footer %}
    <footer>

            <div class="text-center" style="padding-top: 10px">
            	Разработчик <a target="_blank" href="https://vk.com/mechpilot">Антон Егоров</a>
            </div>

</footer>
{% endblock %}

project/project/templates/project/header.html
{% block header %}
    <!--Шапка-->
    <header>
        <nav class="navbar navbar-default " role="navigation">
            <div class="container-fluid">
                <div class="row">

                    <!--логотип и кнопка раздвижения меню-->
                    <div class="col-sm-8">
                        <div class="navbar-header" role="banner">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#navbar-collapse">
                                <span class="sr-only">Развернуть</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            
                            <img src="">
                        </div>
                    </div>

                    <!--навигационое меню сайта -->
                    <div class="col-sm-16">
                        <div class="collapse navbar-collapse" id="navbar-collapse">
                            <ul class="nav  nav-pills nav-justified navMenu">
                                <li class="">
                                    <a href="{% url 'welcome:index' %}">
                                        <i class="" aria-hidden="true"></i> Главная
                                    </a>
                                </li>
                                {% if perms.crm %} 
                                <li class="">
                                    <a href="{% url 'crm:index' %}">
                                        <i class="" aria-hidden="true"></i> Учет посетителей
                                    </a>
                                </li>                               
                                <li class="">
                                    <a href="{% url 'crm:charts' %}">
                                        <i class="" aria-hidden="true"></i> Анализ посещений
                                    </a>
                                </li>
                                {% endif %}



                                {% if user.is_authenticated %}
                                <li>                            
                                        <a href="">*Личный кабинет {{user.username}}</a>
                                </li>
                                <li class="">
                                        <a href="{% url 'registration:logout' %}">Выход</a> 
                                </li>
                                {% else %} 
                                <li>                                    
                                    <a href="{% url 'registration:login' %}">Войдите</a>
                                </li>
                                <li class="">
                                    <a href="{% url 'registration:reg' %}">Зарегистрируйтесь</a>
                                </li>
                                {% endif %}
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}